In [2]:
import pandas as pd
import numpy as np

# Load cleaned dataset
df = pd.read_excel("Cleaned_Data_Set.xlsx")

# Step 1: Dataset overview
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

# Step 2: Basic statistics
print("\nStatistical Summary:")
display(df.describe())

# Step 3: Data quality overview
print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

# Step 4: Total records
total_records = len(df)

print("\nTotal Records:", total_records)

# Step 5: Total metric value
total_metric_value = df["metric_value"].sum()

print("Total Metric Value:", round(total_metric_value, 2))

# Step 6: Average metric value
average_metric_value = df["metric_value"].mean()

print("Average Metric Value:", round(average_metric_value, 2))

# Step 7: Average freshness
average_freshness = df["freshness_hours"].mean()

print("Average Freshness Hours:", round(average_freshness, 2))

# Step 8: Total row count
total_row_count = df["row_count"].sum()

print("Total Row Count:", total_row_count)

# Step 9: Total null count
total_null_count = df["null_count"].sum()

print("Total Null Count:", total_null_count)

# Step 10: Total duplicate count
total_duplicate_count = df["duplicate_count"].sum()

print("Total Duplicate Count:", total_duplicate_count)

# Step 11: Status distribution
status_summary = (
    df["status"]
    .value_counts()
    .reset_index()
)

status_summary.columns = ["status", "count"]

print("\nStatus Distribution:")
display(status_summary)

# Step 12: Alert rate
alert_count = (df["status"] == "ALERT").sum()

alert_rate = (alert_count / total_records) * 100

print("Alert Rate:", round(alert_rate, 2), "%")

# Step 13: Metric-wise analysis
metric_summary = (
    df.groupby("metric_name")
    .agg(
        total_value=("metric_value", "sum"),
        average_value=("metric_value", "mean"),
        record_count=("metric_name", "count"),
        average_freshness=("freshness_hours", "mean"),
        total_nulls=("null_count", "sum"),
        total_duplicates=("duplicate_count", "sum")
    )
    .reset_index()
)

print("\nMetric-wise Analysis:")
display(metric_summary)

# Step 14: Source-system analysis
source_summary = (
    df.groupby("source_system")
    .agg(
        total_value=("metric_value", "sum"),
        average_value=("metric_value", "mean"),
        records=("source_system", "count"),
        average_freshness=("freshness_hours", "mean"),
        total_nulls=("null_count", "sum"),
        total_duplicates=("duplicate_count", "sum")
    )
    .reset_index()
)

print("\nSource System Analysis:")
display(source_summary)

# Step 15: Status-wise analysis
status_analysis = (
    df.groupby("status")
    .agg(
        records=("status", "count"),
        average_freshness=("freshness_hours", "mean"),
        total_nulls=("null_count", "sum"),
        total_duplicates=("duplicate_count", "sum")
    )
    .reset_index()
)

print("\nStatus-wise Analysis:")
display(status_analysis)

# Step 16: Daily analysis
daily_summary = (
    df.groupby("event_date")
    .agg(
        metric_value=("metric_value", "sum"),
        average_freshness=("freshness_hours", "mean"),
        total_nulls=("null_count", "sum"),
        total_duplicates=("duplicate_count", "sum"),
        records=("event_id" if "event_id" in df.columns else "metric_name", "count")
    )
    .reset_index()
)

print("\nDaily Analysis:")
display(daily_summary.head())

# Step 17: Freshness analysis
freshness_summary = (
    df.groupby("source_system")["freshness_hours"]
    .agg(["mean", "min", "max"])
    .reset_index()
)

freshness_summary.columns = [
    "source_system",
    "average_freshness",
    "minimum_freshness",
    "maximum_freshness"
]

print("\nFreshness Analysis:")
display(freshness_summary)

# Step 18: Data-quality analysis
quality_summary = (
    df.groupby("source_system")
    .agg(
        total_records=("metric_name", "count"),
        total_nulls=("null_count", "sum"),
        total_duplicates=("duplicate_count", "sum"),
        average_freshness=("freshness_hours", "mean")
    )
    .reset_index()
)

print("\nData Quality Analysis:")
display(quality_summary)

# Step 19: High freshness records
high_freshness = df[df["freshness_hours"] > 8]

print("\nHigh Freshness Records:")
display(high_freshness.head())

# Step 20: Records with null issues
null_issue_records = df[df["null_count"] > 0]

print("\nRecords With Null Issues:")
display(null_issue_records.head())

# Step 21: Records with duplicate issues
duplicate_issue_records = df[df["duplicate_count"] > 0]

print("\nRecords With Duplicate Issues:")
display(duplicate_issue_records.head())

# Step 22: Alert records
alert_records = df[df["status"] == "ALERT"]

print("\nAlert Records:")
display(alert_records.head())

# Step 23: Top metrics by total value
top_metrics = (
    metric_summary
    .sort_values("total_value", ascending=False)
)

print("\nTop Metrics:")
display(top_metrics)

# Step 24: Source systems by metric value
top_sources = (
    source_summary
    .sort_values("total_value", ascending=False)
)

print("\nSource Systems by Metric Value:")
display(top_sources)

# Step 25: Overall business insights
print("\nBUSINESS INSIGHTS")

print(
    "1. Total records analyzed:",
    total_records
)

print(
    "2. Total metric value:",
    round(total_metric_value, 2)
)

print(
    "3. Average metric value:",
    round(average_metric_value, 2)
)

print(
    "4. Average freshness:",
    round(average_freshness, 2),
    "hours"
)

print(
    "5. Alert rate:",
    round(alert_rate, 2),
    "%"
)

print(
    "6. Total null count:",
    total_null_count
)

print(
    "7. Total duplicate count:",
    total_duplicate_count
)

# Step 26: Final analysis table
final_summary = pd.DataFrame({
    "Metric": [
        "Total Records",
        "Total Metric Value",
        "Average Metric Value",
        "Average Freshness Hours",
        "Alert Rate",
        "Total Null Count",
        "Total Duplicate Count"
    ],
    "Value": [
        total_records,
        round(total_metric_value, 2),
        round(average_metric_value, 2),
        round(average_freshness, 2),
        round(alert_rate, 2),
        total_null_count,
        total_duplicate_count
    ]
})

print("\nFinal Summary:")
display(final_summary)

# Save one analysis result
final_summary.to_excel("Python_Analysis_Result.xlsx", index=False)

print("\nAnalysis completed successfully.")

Dataset Shape: (200, 9)

Columns:
['event_date', 'metric_name', 'metric_value', 'source_system', 'freshness_hours', 'row_count', 'null_count', 'duplicate_count', 'status']

Data Types:
event_date         datetime64[ns]
metric_name                object
metric_value                int64
source_system              object
freshness_hours             int64
row_count                   int64
null_count                  int64
duplicate_count             int64
status                     object
dtype: object

Statistical Summary:

,event_date,metric_value,freshness_hours,row_count,null_count,duplicate_count
count,200,200.000000,200.000000,200.000000,200.000000,200.000000
mean,2026-07-15 02:24:00,2676.920000,7.675000,3059.170000,9.685000,5.075000
min,2026-07-01 00:00:00,51.000000,1.000000,1007.000000,0.000000,0.000000
25%,2026-07-08 00:00:00,1547.250000,2.000000,1899.750000,5.000000,2.000000
50%,2026-07-15 00:00:00,2742.000000,4.000000,3111.500000,10.000000,5.000000
75%,2026-07-22 00:00:00,3882.500000,8.000000,4161.000000,14.000000,8.000000
max,2026-07-30 00:00:00,4928.000000,24.000000,4995.000000,20.000000,10.000000
std,NaN,1398.152612,8.403719,1231.860431,5.565126,3.117365

Missing Values:
event_date         0
metric_name        0
metric_value       0
source_system      0
freshness_hours    0
row_count          0
null_count         0
duplicate_count    0
status             0
dtype: int64

Duplicate Rows:
0

Total Records: 200
Total Metric Value: 535384
Average Metric Value: 2676.92
Average Freshness Hours: 7.68
Total Row Count: 611834
Total Null Count: 1937
Total Duplicate Count: 1015

Status Distribution:

  status  count
0  ALERT    199
1   PASS      1

Alert Rate: 99.5 %

Metric-wise Analysis:

,metric_name,total_value,average_value,record_count,average_freshness,total_nulls,total_duplicates
0,active_users,110149,2159.784314,51,8.313725,576,268
1,daily_orders,115280,2882.000000,40,8.850000,355,209
2,refunds,135654,2886.255319,47,7.808511,398,233
3,revenue,174301,2811.306452,62,6.290323,608,305

Source System Analysis:

,source_system,total_value,average_value,records,average_freshness,total_nulls,total_duplicates
0,App,174242,2562.382353,68,8.720588,656,372
1,Erp,172519,2738.396825,63,8.301587,619,337
2,Warehouse,188623,2733.666667,69,6.072464,662,306

Status-wise Analysis:

  status  records  average_freshness  total_nulls  total_duplicates
0  ALERT      199           7.693467         1937              1015
1   PASS        1           4.000000            0                 0

Daily Analysis:

,event_date,metric_value,average_freshness,total_nulls,total_duplicates,records
0,2026-07-01,8928,7.833333,58,31,6
1,2026-07-02,21676,5.571429,81,41,7
2,2026-07-03,28280,5.714286,95,34,7
3,2026-07-04,18756,10.000000,52,31,7
4,2026-07-05,18318,5.000000,65,36,7

Freshness Analysis:

  source_system  average_freshness  minimum_freshness  maximum_freshness
0           App           8.720588                  1                 24
1           Erp           8.301587                  1                 24
2     Warehouse           6.072464                  1                 24

Data Quality Analysis:

,source_system,total_records,total_nulls,total_duplicates,average_freshness
0,App,68,656,372,8.720588
1,Erp,63,619,337,8.301587
2,Warehouse,69,662,306,6.072464

High Freshness Records:

,event_date,metric_name,metric_value,source_system,freshness_hours,row_count,null_count,duplicate_count,status
3,2026-07-01,refunds,127,App,24,4352,1,3,ALERT
6,2026-07-02,revenue,4620,App,24,3118,4,8,ALERT
17,2026-07-03,refunds,3968,Erp,24,4609,17,4,ALERT
21,2026-07-04,revenue,4832,Erp,24,3624,15,5,ALERT
24,2026-07-04,active_users,147,Warehouse,24,1315,9,10,ALERT

Records With Null Issues:

,event_date,metric_name,metric_value,source_system,freshness_hours,row_count,null_count,duplicate_count,status
0,2026-07-01,revenue,3731,Warehouse,1,2488,4,2,ALERT
1,2026-07-01,daily_orders,522,App,2,3105,19,5,ALERT
2,2026-07-01,active_users,1094,Erp,8,2818,12,6,ALERT
3,2026-07-01,refunds,127,App,24,4352,1,3,ALERT
4,2026-07-01,refunds,928,Erp,8,1396,6,10,ALERT

Records With Duplicate Issues:

,event_date,metric_name,metric_value,source_system,freshness_hours,row_count,null_count,duplicate_count,status
0,2026-07-01,revenue,3731,Warehouse,1,2488,4,2,ALERT
1,2026-07-01,daily_orders,522,App,2,3105,19,5,ALERT
2,2026-07-01,active_users,1094,Erp,8,2818,12,6,ALERT
3,2026-07-01,refunds,127,App,24,4352,1,3,ALERT
4,2026-07-01,refunds,928,Erp,8,1396,6,10,ALERT

Alert Records:

,event_date,metric_name,metric_value,source_system,freshness_hours,row_count,null_count,duplicate_count,status
0,2026-07-01,revenue,3731,Warehouse,1,2488,4,2,ALERT
1,2026-07-01,daily_orders,522,App,2,3105,19,5,ALERT
2,2026-07-01,active_users,1094,Erp,8,2818,12,6,ALERT
3,2026-07-01,refunds,127,App,24,4352,1,3,ALERT
4,2026-07-01,refunds,928,Erp,8,1396,6,10,ALERT

Top Metrics:

,metric_name,total_value,average_value,record_count,average_freshness,total_nulls,total_duplicates
3,revenue,174301,2811.306452,62,6.290323,608,305
2,refunds,135654,2886.255319,47,7.808511,398,233
1,daily_orders,115280,2882.000000,40,8.850000,355,209
0,active_users,110149,2159.784314,51,8.313725,576,268

Source Systems by Metric Value:

,source_system,total_value,average_value,records,average_freshness,total_nulls,total_duplicates
2,Warehouse,188623,2733.666667,69,6.072464,662,306
0,App,174242,2562.382353,68,8.720588,656,372
1,Erp,172519,2738.396825,63,8.301587,619,337

BUSINESS INSIGHTS
1. Total records analyzed: 200
2. Total metric value: 535384
3. Average metric value: 2676.92
4. Average freshness: 7.68 hours
5. Alert rate: 99.5 %
6. Total null count: 1937
7. Total duplicate count: 1015

Final Summary:

                    Metric      Value
0            Total Records     200.00
1       Total Metric Value  535384.00
2     Average Metric Value    2676.92
3  Average Freshness Hours       7.68
4               Alert Rate      99.50
5         Total Null Count    1937.00
6    Total Duplicate Count    1015.00

Analysis completed successfully.